### PR TITLE
Redesign dispatch menu

### PR DESCRIPTION
**Pull request by wbolster**
* use better groupings
* use multi-column visual layout
* add some more flags
* make all flags start with either ``-`` or ``--`` (mostly mimicking pytest flags)

### CODE REVIEW

**Comment by wbolster** [comment]
as follow-up to some comments from #26... what do you think of this, @pkryger?

image

(somehow hard to copy/paste the text from the popup, so here's an image instead)

**Comment by pkryger** [comment]
I like the new layout with logical groping much better. (I also like the theme - a `solarized-light` user here ☀️). 

I used a way to programmatically copy contents of `*transient*` buffer to a `*scratch*` and then copy text via clipboard. Thinking 🤔 of it now I should have probably been using `(kill-new)`. Will find it and post later, when I get to a computer.

I've also noticed that in readme I put a code from a sample popup instead of the `python-pytest-dispatch`🤭. Will send a PR with an improved example.

**Comment by wbolster** [comment]
some questions/doubts/thoughts:

- using multiple columns for flags/options? magit doesn't do it, but usually has fewer of them i think it visually helps and since many of them are short it fits even on small screens, and saves a lot of vertical space

- got rid of all key bindings starting with `=` since it's not required anymore, and some of the previous `=` flags didn't correspond to real pytest short options anyway.

- use `--foo` options with double dash instead. some of them actually match (a prefix of) real pytest options (e.g. `--lf`), while others do not (`--ft` for `--full-trace`). is this too confusing or messy?

- do the groupings make sense? maybe it can be reduced a bit?

- should other options be added/removed?

**Comment by pkryger** [comment]
Here's the trick to have a new kill item ready to yank rigth after invoking a popup/dispatch:
``` elisp
(define-advice python-pytest-dispatch (:after (&rest _))
  (with-current-buffer transient--buffer-name
    (copy-region-as-kill (point-min) (point-max))))
```

> * using multiple columns for flags/options? magit doesn't do it, but usually has fewer of them. i think it visually helps and since many of them are short it fits even on small screens, and saves a lot of vertical space

Same thoughts.

> * got rid of all key bindings starting with `=` since it's not required anymore, and some of the previous `=` flags didn't correspond to real pytest short options anyway.
> * use `--foo` options with double dash instead. some of them actually match (a prefix of) real pytest options (e.g. `--lf`), while others do not (`--ft` for `--full-trace`). is this too confusing or messy?

I like the idea of not having the `=` things anymore. The fact that some options double dash flags don't have corresponding `pytest` options is fine as well. As long as they don't step on any other `pytest` option I'm fine. I think that comes from the way I use transient: firstly it's  a helper to explore options (with reasonable defaults), later it's muscle memory - I don't even read it - just blindly hit `P -f p` to push an amended commit 🤗. Not sure how open the `pytest` would be to accept these new switches 🤔


> * do the groupings make sense? maybe it can be reduced a bit?

Perhaps the `Exit early` could be merged into `Test selection and ordering`. The exit early could be interpreted as a dynamic filter 🤔

> * should other options be added/removed?

Not an expert here as I don't do much `python` 🤭😜. And IDK a good way of measuring it, unless you want to snoop on users' choices into some analytic cloud... but somehow I don't like that. Perhaps having a paragraph in a prominent place in the readme asking people to send their requests for missing options?

**Comment by wbolster** [comment]
i fiddled some more. this is what it looks like now:

```
Output                                                                                                                                                                                                                    
 -c color (--color)                                                                                                                                                                                                       
 -q quiet (--quiet)                                                                                                                                                                                                       
 -s no output capture (--capture=no)                                                                                                                                                                                      
 -v verbosity ([--verbose|--verbose --verbose])                                                                                                                                                                           
                                                                                                                                                                                                                          
Selection, filtering, ordering                                                                                                                                                                                            
 -k only names matching expression (-k=)      --dm run doctests (--doctest-modules)                                                                                                                                       
 -m only marks matching expression (-m=)      --nf new first (--new-first)                                                                                                                                                
                                              --sw stepwise (--stepwise)                                                                                                                                                  
                                                                                                                                                                                                                          
Failures, errors, debugging                                                                                                                                                                                               
 -l show locals (--showlocals)                --ff failed first (--failed-first)                                                                                                                                          
 -p debug on error (--pdb)                    --ft full tracebacks (--full-trace)                                                                                                                                         
 -x exit after first failure (--exitfirst)    --mf exit after N failures or errors (--maxfail=10)                                                                                                                         
                                              --rx run xfail tests (--runxfail)                                                                                                                                           
                                              --tb traceback style (--tb=)                                                                                                                                                
                                              --tr debug on each test (--trace)                                                                                                                                           
                                                                                                                                                                                                                          
Run tests                                                                                                                                                                                                                 
 t all    r repeat         f file (dwim)    m files          d def/class (dwim)                                                                                                                                           
          x last failed    f this file      m directories    d this def/class                                                                                                                                             
```

pretty happy with it. unless @pkryger has some suggestions that need further work,
i'll likely merge this soon.

**Comment by pkryger** [comment]
IMO, it looks really good 👍

**Comment by wbolster** [comment]
cool, thanks for your review and previous input!

**Pull request merged**
